#!/usr/bin/env python3
"""Split the baseline catalog seed (backend V3__baseline_seed.sql at a3520e1) into the
Specification and Formulation service seeds (G2-M1.3, STCN-66; architecture v3 section 7.4).

IDs, version numbers and timestamps are preserved. Organisations are derived deterministically:
each baseline supplier becomes a SUPPLIER organisation and each brand_owner (case-insensitive)
a MANUFACTURER organisation. Re-running produces byte-identical output.

Usage: python3 perf/data/split_baseline_seed.py   (from the repository root)
"""
import csv
import io
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASELINE = ROOT / "backend/src/main/resources/db/migration/V3__baseline_seed.sql"
SPEC_OUT = ROOT / "services/specification/src/main/resources/db/migration/V2__baseline_seed.sql"
FORM_OUT = ROOT / "services/formulation/src/main/resources/db/migration/V2__baseline_seed.sql"
ORG_OUT = ROOT / "docs/swe5001/data/organisations.csv"

SEED_SUBJECT = "baseline:user_admin"


def rows(sql, table):
    """Parse the VALUES tuples of `INSERT INTO <table> (...) VALUES ...;` blocks."""
    result = []
    for match in re.finditer(r"INSERT INTO `?%s`? \(([^)]*)\) VALUES\s*(.*?);\s*$" % table, sql, re.S | re.M):
        columns = [c.strip() for c in match.group(1).split(",")]
        for values in tuples(match.group(2)):
            result.append(dict(zip(columns, values)))
    return result


def tuples(text):
    i, out = 0, []
    while i < len(text):
        if text[i] != "(":
            i += 1
            continue
        i += 1
        values, current, quoted = [], "", False
        while True:
            ch = text[i]
            if quoted:
                if ch == "'" and text[i + 1] == "'":
                    current += "'"
                    i += 2
                    continue
                if ch == "'":
                    quoted = False
                    i += 1
                    continue
                current += ch
            elif ch == "'":
                quoted = True
                current = current.strip() + "\0"
            elif ch in ",)":
                token = current.strip()
                values.append(None if token == "NULL" else token.lstrip("\0"))
                current = ""
                if ch == ")":
                    i += 1
                    break
            else:
                current += ch
            i += 1
        out.append(values)
    return out


def q(value):
    return "NULL" if value is None else "'" + str(value).replace("'", "''") + "'"


def insert(table, columns, records):
    lines = [f"INSERT INTO {table} ({', '.join(columns)}) VALUES"]
    lines.append(",\n".join("(" + ", ".join(q(r[c]) for c in columns) + ")" for r in records) + ";")
    return "\n".join(lines) + "\n"


def slug(text):
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")[:100]


def main():
    sql = BASELINE.read_text(encoding="utf-8")
    provenance = rows(sql, "data_provenance")
    suppliers = rows(sql, "supplier")
    ingredients = rows(sql, "ingredient")
    materials = rows(sql, "supplier_material")
    specs = rows(sql, "ingredient_specification_version")
    components = rows(sql, "spec_component")
    products = rows(sql, "product")
    formulas = rows(sql, "formula_version")
    items = rows(sql, "formula_item")
    # The baseline sets current pointers with UPDATE statements after the formula and label inserts.
    pointers = {pid: fid for fid, pid in re.findall(
        r"UPDATE product SET current_formula_version_id='([^']+)'[^;]*WHERE product_id='([^']+)';", sql)}
    for p in products:
        p["current_formula_version_id"] = pointers.get(p["product_id"], p.get("current_formula_version_id"))

    organisations = {}
    for s in suppliers:
        s["organisation_id"] = "supplier_" + slug(s["supplier_id"].removeprefix("sup_"))
        organisations[s["organisation_id"]] = ("SUPPLIER", s["supplier_name"], s["supplier_id"])
    for p in products:
        p["organisation_id"] = "manufacturer_" + slug(p["brand_owner"])
        organisations.setdefault(p["organisation_id"], ("MANUFACTURER", p["brand_owner"], None))

    used_provenance = {r["data_provenance_id"] for r in suppliers + ingredients + materials + specs + products + formulas}
    prov_columns = ["provenance_id", "source_type", "source_dataset", "source_record_id", "source_url",
                    "source_snapshot_date", "derivation_rule", "synthetic_reason", "created_at", "created_by"]
    prov = [r for r in provenance if r["provenance_id"] in used_provenance]

    header = ("-- Generated by perf/data/split_baseline_seed.py from backend V3__baseline_seed.sql (baseline a3520e1).\n"
              "-- Do not edit by hand. IDs, version numbers and timestamps are preserved (architecture v3 section 7.4).\n\n")

    spec_prov = [r for r in prov if r["provenance_id"] in {x["data_provenance_id"] for x in suppliers + ingredients + materials + specs}]
    material_by_id = {m["supplier_material_id"]: m for m in materials}
    spec_sql = header
    spec_sql += insert("provenance", prov_columns, spec_prov) + "\n"
    spec_sql += insert("supplier", ["supplier_id", "organisation_id", "supplier_code", "supplier_name", "provenance_id"],
                       [{**s, "provenance_id": s["data_provenance_id"]} for s in suppliers]) + "\n"
    spec_sql += insert("ingredient", ["ingredient_id", "canonical_name", "ingredient_kind", "source_type", "provenance_id"],
                       [{**i, "provenance_id": i["data_provenance_id"]} for i in ingredients]) + "\n"
    spec_sql += insert("material", ["material_id", "supplier_id", "ingredient_id", "material_code", "material_name",
                                    "material_description", "provenance_id"],
                       [{**m, "material_id": m["supplier_material_id"], "provenance_id": m["data_provenance_id"]} for m in materials]) + "\n"
    spec_sql += insert("specification_version", ["specification_version_id", "material_id", "version_number", "lifecycle_status",
                                                 "effective_date", "released_at", "created_by_subject", "provenance_id"],
                       [{**s, "material_id": s["supplier_material_id"], "created_by_subject": SEED_SUBJECT,
                         "provenance_id": s["data_provenance_id"]} for s in specs]) + "\n"
    spec_sql += insert("spec_component", ["spec_component_id", "specification_version_id", "sequence_no", "ingredient_id",
                                          "raw_phrase", "match_rule", "match_status"], components)

    supplier_by_id = {s["supplier_id"]: s for s in suppliers}
    form_prov = [r for r in prov if r["provenance_id"] in {x["data_provenance_id"] for x in products + formulas + specs}]
    form_sql = header
    form_sql += insert("provenance", prov_columns, form_prov) + "\n"
    form_sql += insert("product", ["product_id", "organisation_id", "fdc_id", "gtin_upc", "brand_owner", "brand_name",
                                   "product_description", "branded_food_category", "normalized_category", "market_country",
                                   "publication_date", "source_ingredients_text", "source_type", "fixture_group", "provenance_id"],
                       [{**p, "provenance_id": p["data_provenance_id"]} for p in products]) + "\n"
    # Released-spec projection as if the bootstrap SpecificationPublished events had been applied (STCN-115).
    released = [s for s in specs if s["lifecycle_status"] in ("RELEASED", "RETIRED")]
    form_sql += insert("released_spec_projection", ["specification_version_id", "material_id", "version_number", "supplier_id",
                                                    "supplier_organisation_id", "effective_date", "released_at", "received_at",
                                                    "provenance_id"],
                       [{"specification_version_id": s["specification_version_id"], "material_id": s["supplier_material_id"],
                         "version_number": s["version_number"],
                         "supplier_id": material_by_id[s["supplier_material_id"]]["supplier_id"],
                         "supplier_organisation_id": supplier_by_id[material_by_id[s["supplier_material_id"]]["supplier_id"]]["organisation_id"],
                         "effective_date": s["effective_date"], "released_at": s["released_at"], "received_at": s["released_at"],
                         "provenance_id": s["data_provenance_id"]} for s in released]) + "\n"
    form_sql += insert("formula_version", ["formula_version_id", "product_id", "version_number", "lifecycle_status",
                                           "is_current_released", "created_by_subject", "released_by_subject", "released_at",
                                           "provenance_id"],
                       [{**f, "is_current_released": "1" if f["is_current_released"] == "Y" else "0",
                         "created_by_subject": SEED_SUBJECT,
                         "released_by_subject": SEED_SUBJECT if f["released_by_user_id"] else None,
                         "provenance_id": f["data_provenance_id"]} for f in formulas]) + "\n"
    spec_number = {s["specification_version_id"]: s["version_number"] for s in specs}
    form_sql += insert("formula_item", ["formula_item_id", "formula_version_id", "sequence_no", "material_id",
                                        "specification_version_id", "specification_version_number", "quantity_value", "quantity_unit"],
                       [{**i, "material_id": i["supplier_material_id"],
                         "specification_version_number": spec_number[i["specification_version_id"]]} for i in items]) + "\n"
    form_sql += "".join(f"UPDATE product SET current_formula_version_id = {q(p['current_formula_version_id'])} "
                        f"WHERE product_id = {q(p['product_id'])};\n" for p in products if p["current_formula_version_id"])

    SPEC_OUT.write_text(spec_sql, encoding="utf-8")
    FORM_OUT.write_text(form_sql, encoding="utf-8")

    ORG_OUT.parent.mkdir(parents=True, exist_ok=True)
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(["organisation_id", "organisation_type", "display_name", "baseline_supplier_id"])
    for org_id in sorted(organisations):
        org_type, name, supplier_id = organisations[org_id]
        writer.writerow([org_id, org_type, name, supplier_id or ""])
    ORG_OUT.write_text(buffer.getvalue(), encoding="utf-8")
    print(f"suppliers={len(suppliers)} materials={len(materials)} specs={len(specs)} components={len(components)} "
          f"products={len(products)} formulas={len(formulas)} items={len(items)} organisations={len(organisations)} "
          f"(manufacturers={sum(1 for v in organisations.values() if v[0] == 'MANUFACTURER')})")


if __name__ == "__main__":
    main()
