sonar.organization=hxj04121-lab
sonar.projectKey=hxj04121-lab_FoodLabelFlow-Microservices
sonar.projectName=FoodLabelFlow-Microservices
sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,bootstrap_inputs/**,.stage0/**
