-- Generated by perf/data/split_baseline_seed.py from backend V3__baseline_seed.sql (baseline a3520e1).
-- Do not edit by hand. IDs, version numbers and timestamps are preserved (architecture v3 section 7.4).

INSERT INTO provenance (provenance_id, source_type, source_dataset, source_record_id, source_url, source_snapshot_date, derivation_rule, synthetic_reason, created_at, created_by) VALUES
('prov_project_seed', 'PROJECT_SEEDED', 'SpecTrace SWE5006 v3 fixture', NULL, NULL, '2026-09-01', 'Project-seeded supplier/material/formula relationships for deterministic demo.', 'USDA product records do not publish supplier material relationships.', '2026-09-01 00:00:00', 'build_spectrace_v3_package.py');

INSERT INTO supplier (supplier_id, organisation_id, supplier_code, supplier_name, provenance_id) VALUES
('sup_chocolate_demo', 'supplier_chocolate_demo', 'CHOCO_SUP', 'Demo Chocolate Supplier', 'prov_project_seed'),
('sup_base_demo', 'supplier_base_demo', 'BASE_SUP', 'Demo Base Ingredients Supplier', 'prov_project_seed');

INSERT INTO ingredient (ingredient_id, canonical_name, ingredient_kind, source_type, provenance_id) VALUES
('ing_chocolate', 'Chocolate Base Ingredient', 'COMPOUND', 'PROJECT_SEEDED', 'prov_project_seed'),
('ing_cocoa', 'Cocoa', 'CANONICAL', 'PROJECT_SEEDED', 'prov_project_seed'),
('ing_sugar', 'Sugar', 'CANONICAL', 'PROJECT_SEEDED', 'prov_project_seed'),
('ing_soy_lecithin', 'Soy Lecithin', 'CANONICAL', 'PROJECT_SEEDED', 'prov_project_seed'),
('ing_wheat_flour', 'Wheat Flour', 'CANONICAL', 'PROJECT_SEEDED', 'prov_project_seed'),
('ing_milk_powder', 'Milk Powder', 'CANONICAL', 'PROJECT_SEEDED', 'prov_project_seed'),
('ing_neutral_base', 'Neutral Base', 'PLACEHOLDER', 'PROJECT_SEEDED', 'prov_project_seed');

INSERT INTO material (material_id, supplier_id, ingredient_id, material_code, material_name, material_description, provenance_id) VALUES
('mat_chocolate_base', 'sup_chocolate_demo', 'ing_chocolate', 'CHOC_BASE', 'Chocolate Base', 'Project-seeded material used by 40 demo products.', 'prov_project_seed'),
('mat_soy_carrier', 'sup_base_demo', 'ing_soy_lecithin', 'SOY_CARRIER', 'Soy Carrier', 'Project-seeded soy-containing formula item.', 'prov_project_seed'),
('mat_neutral_base', 'sup_base_demo', 'ing_neutral_base', 'NEUTRAL_BASE', 'Neutral Base', 'Project-seeded neutral formula item with no controlled allergen.', 'prov_project_seed'),
('mat_wheat_flour', 'sup_base_demo', 'ing_wheat_flour', 'WHEAT_FLOUR', 'Wheat Flour', 'Project-seeded wheat-containing formula item.', 'prov_project_seed'),
('mat_milk_powder', 'sup_base_demo', 'ing_milk_powder', 'MILK_POWDER', 'Milk Powder', 'Project-seeded milk-containing formula item.', 'prov_project_seed');

INSERT INTO specification_version (specification_version_id, material_id, version_number, lifecycle_status, effective_date, released_at, created_by_subject, provenance_id) VALUES
('spec_chocolate_v1', 'mat_chocolate_base', '1', 'RELEASED', '2026-01-01', '2026-01-01 09:00:00', 'baseline:user_admin', 'prov_project_seed'),
('spec_soy_carrier_v1', 'mat_soy_carrier', '1', 'RELEASED', '2026-01-01', '2026-01-01 09:00:00', 'baseline:user_admin', 'prov_project_seed'),
('spec_neutral_base_v1', 'mat_neutral_base', '1', 'RELEASED', '2026-01-01', '2026-01-01 09:00:00', 'baseline:user_admin', 'prov_project_seed'),
('spec_wheat_flour_v1', 'mat_wheat_flour', '1', 'RELEASED', '2026-01-01', '2026-01-01 09:00:00', 'baseline:user_admin', 'prov_project_seed'),
('spec_milk_powder_v1', 'mat_milk_powder', '1', 'RELEASED', '2026-01-01', '2026-01-01 09:00:00', 'baseline:user_admin', 'prov_project_seed');

INSERT INTO spec_component (spec_component_id, specification_version_id, sequence_no, ingredient_id, raw_phrase, match_rule, match_status) VALUES
('sc_chocolate_v1_cocoa', 'spec_chocolate_v1', '1', 'ing_cocoa', 'Cocoa', 'Project fixture component', 'MATCHED'),
('sc_chocolate_v1_sugar', 'spec_chocolate_v1', '2', 'ing_sugar', 'Sugar', 'Project fixture component', 'MATCHED'),
('sc_soy_carrier_v1_soy', 'spec_soy_carrier_v1', '1', 'ing_soy_lecithin', 'Soy lecithin', 'Project fixture component', 'MATCHED'),
('sc_neutral_base_v1_neutral', 'spec_neutral_base_v1', '1', 'ing_neutral_base', 'Neutral base', 'Project fixture component', 'MATCHED'),
('sc_wheat_flour_v1_wheat', 'spec_wheat_flour_v1', '1', 'ing_wheat_flour', 'Wheat flour', 'Project fixture component', 'MATCHED'),
('sc_milk_powder_v1_milk', 'spec_milk_powder_v1', '1', 'ing_milk_powder', 'Milk powder', 'Project fixture component', 'MATCHED');
